## Airbnb

In [1]:
import numpy as np
import pandas as pd
from dateutil import parser

import matplotlib.pyplot as plt
import matplotlib as mpl
mpl.rcParams['figure.figsize'] = [10,6]
mpl.rcParams['figure.dpi'] = 80
mpl.rcParams['savefig.dpi'] = 200
mpl.rcParams['font.size'] = 17
mpl.rcParams['legend.fontsize'] = 'large'
mpl.rcParams['figure.titlesize'] = 'medium'
mpl.rcParams['lines.linewidth'] = 2.5
mpl.rcParams['lines.markersize'] = 10

In [4]:
# Load file
df_airbnb = pd.read_csv('airbnb.csv', sep=',')
df_airbnb = df_airbnb.sort_values(by=['found'], ascending=True)
df_airbnb.head()

,id,url,longitude,latitude,found,revised,host-id,room_type,bedrooms,capacity,reviews,min_nights,price
2646,airbnb599230b08a46554edf8846652647,https://www.airbnb.es/rooms/17590535,1.810000,41.721000,2017-08-14 21:31:25.122000,2018-06-03 23:42:30.030000,airbnb53431957,entire_home,1.0,4,38,1,102.0
2620,airbnb599230b08a46554edf8846652621,https://www.airbnb.es/rooms/17781416,1.703671,41.774020,2017-08-14 21:31:25.123000,2018-06-04 03:19:39.881000,airbnb121163023,private_room,1.0,3,35,1,28.0
2663,airbnb599230b08a46554edf8846652664,https://www.airbnb.es/rooms/4812499,1.825780,41.723410,2017-08-14 21:31:25.123000,2018-09-23 08:16:54.982000,airbnb24786440,entire_home,0.0,4,132,2,NaN
2673,airbnb599230b08a46554edf8846652674,https://www.airbnb.es/rooms/11581772,1.827224,41.722807,2017-08-14 21:31:25.123000,2018-09-23 07:25:51.054000,airbnb23283540,entire_home,0.0,6,23,1,NaN
36901,airbnb599230b08a46554edf88466536902,https://www.airbnb.es/rooms/16642190,1.684489,41.920700,2017-08-14 21:31:25.123000,2018-06-04 03:19:59.351000,airbnb109970375,entire_home,3.0,5,19,2,108.0

In [3]:
date_start = '2017-08-01'

0        2018-08-25 15:34:45.776000
1        2017-08-15 04:47:07.766000
2        2018-04-05 22:28:44.396000
3        2017-08-15 04:47:23.920000
4        2018-08-25 15:34:47.770000
5        2017-08-15 04:47:28.038000
6        2018-05-04 14:12:29.449000
7        2017-08-15 04:47:23.920000
8        2017-08-25 05:08:19.103000
9        2018-04-24 02:38:18.266000
10       2017-08-15 04:47:28.037000
11       2017-08-25 05:08:19.103000
12       2017-08-26 13:05:33.397000
13       2018-08-27 12:49:25.409000
14       2018-08-25 15:34:45.776000
15       2018-05-04 14:12:29.449000
16       2018-01-17 00:42:58.565000
17       2018-04-24 02:38:18.266000
18       2017-08-15 04:47:15.553000
19       2018-04-05 22:37:35.251000
20       2017-08-15 04:47:32.211000
21       2018-04-05 22:28:44.396000
22       2017-08-15 04:47:32.211000
23       2017-08-15 04:47:11.554000
24       2017-08-15 04:47:32.211000
25       2017-08-15 04:47:03.751000
26       2017-08-25 05:08:23.368000
27       2017-08-15 04:47:07.766000
28       2017-08-15 04:47:32.210000
29       2017-08-15 04:47:03.751000
                    ...
39114    2018-04-08 02:41:46.052000
39115    2017-08-15 04:53:32.052000
39116    2018-05-06 19:46:38.213000
39117    2018-04-08 02:42:56.649000
39118    2017-08-15 04:54:01.720000
39119    2017-08-15 04:53:53.178000
39120    2018-05-11 14:48:08.417000
39121    2018-05-11 14:48:08.418000
39122    2018-04-08 02:43:02.258000
39123    2017-08-15 04:53:57.374000
39124    2017-08-15 04:54:01.719000
39125    2018-05-06 19:45:45.644000
39126    2017-08-25 05:14:45.976000
39127    2017-08-15 04:54:40.507000
39128    2018-04-08 02:41:46.052000
39129    2017-08-15 04:53:53.178000
39130    2017-08-15 04:54:01.720000
39131    2017-08-15 04:53:32.052000
39132    2017-08-15 04:54:05.484000
39133    2017-08-25 05:14:09.112000
39134    2017-08-15 04:53:36.178000
39135    2017-08-15 04:53:49.041000
39136    2017-08-15 04:53:40.540000
39137    2018-04-08 02:43:02.257000
39138    2018-05-25 04:58:54.991000
39139    2017-08-15 04:53:49.041000
39140    2018-05-08 23:41:44.292000
39141    2017-08-15 04:53:57.374000
39142    2018-05-25 04:59:08.561000
39143    2017-08-15 04:53:53.180000
Name: found, Length: 39144, dtype: object