## Airbnb

In [20]:
import numpy as np
import pandas as pd

from dateutil import parser
from dateutil.relativedelta import relativedelta

from datetime import timedelta
from datetime import datetime

import matplotlib.pyplot as plt
import matplotlib as mpl
mpl.rcParams['figure.figsize'] = [10,6]
mpl.rcParams['figure.dpi'] = 80
mpl.rcParams['savefig.dpi'] = 200
mpl.rcParams['font.size'] = 17
mpl.rcParams['legend.fontsize'] = 'large'
mpl.rcParams['figure.titlesize'] = 'medium'
mpl.rcParams['lines.linewidth'] = 2.5
mpl.rcParams['lines.markersize'] = 10

In [6]:
# Load file
df_airbnb = pd.read_csv('data/2018-01.csv', sep=',')
df_airbnb.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,18653,Modern apartment well connected,71615,Mireia And Maria,Eixample,la Sagrada Família,41.409215,2.173868,Entire home/apt,151,2,0,NaN,NaN,29,85
1,18666,Flat with Sunny Terrace,71615,Mireia And Maria,Sant Martí,el Camp de l'Arpa del Clot,41.408886,2.185545,Entire home/apt,130,3,1,2015-10-10,0.04,29,90
2,18674,Huge flat for 8 people close to Sagrada Familia,71615,Mireia And Maria,Eixample,la Sagrada Família,41.404197,2.173058,Entire home/apt,95,3,4,2016-06-20,0.07,29,318
3,19157,"Great Place in Sagrada Familia, Bcn",73099,Urania,Eixample,la Sagrada Família,41.407929,2.174540,Private room,30,2,150,2018-01-03,24.46,2,129
4,19246,Double room in Spacious & nice Flat,73385,Delphine,Eixample,la Nova Esquerra de l'Eixample,41.382735,2.150270,Private room,50,2,66,2017-10-12,0.68,4,365

In [39]:
start_date = "2018-04-01"
stop_date = "2018-09-01"

start = datetime.strptime(start_date, "%Y-%m-%d")
stop = datetime.strptime(stop_date, "%Y-%m-%d")

path = 'data/'+start.strftime('%Y-%m')+'.csv'
df_airbnb = pd.read_csv(path, sep=',')
last_month_ids = df_airbnb.id.values

while start < stop:
    start = start + relativedelta(months=+1)
    path = 'data/'+start.strftime('%Y-%m')+'.csv'
    df_airbnb = pd.read_csv(path, sep=',')
    current_month_ids = df_airbnb.id.values
    print start.strftime('%Y-%m')
    print 'last month', len(last_month_ids)
    print 'current month', len(current_month_ids)
    print 'new listings', len(current_month_ids) - len(np.intersect1d(last_month_ids, df_airbnb.id.values))
    print 'erased listings', len(last_month_ids) - len(np.intersect1d(last_month_ids, df_airbnb.id.values))
    print '\n'
    
    last_month_ids = current_month_ids

2018-05
last month 19168
current month 18919
new listings 1895
erased listings 2144


2018-06
last month 18919
current month 17221
new listings 2056
erased listings 3754


2018-07
last month 17221
current month 17788
new listings 2126
erased listings 1559


2018-08
last month 17788
current month 19261
new listings 4284
erased listings 2811


2018-09
last month 19261
current month 19200
new listings 1942
erased listings 2003